# Generated by Django 2.2.28 on 2024-11-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=100)),
                ('leave_short_form', models.CharField(max_length=10)),
                ('leave_count', models.IntegerField()),
                ('updated_by', models.CharField(max_length=50)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
