# Generated by Django 2.2.28 on 2024-11-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate_id', models.CharField(max_length=10)),
                ('leave_year', models.IntegerField()),
                ('leave_year_start', models.DateField()),
                ('leave_year_end', models.DateField()),
                ('casual_leave', models.IntegerField()),
                ('cl_carry', models.BooleanField(default=False)),
                ('earned_leave', models.IntegerField()),
                ('el_carry', models.BooleanField(default=False)),
                ('sick_leave', models.IntegerField()),
                ('sl_carry', models.BooleanField(default=False)),
                ('paternity_leave', models.IntegerField()),
                ('pl_carry', models.BooleanField(default=False)),
                ('maternity_leave', models.IntegerField()),
                ('ml_carry', models.BooleanField(default=False)),
                ('loss_of_pay', models.IntegerField()),
                ('lop_carry', models.BooleanField(default=False)),
                ('compensatory_off', models.IntegerField()),
                ('co_carry', models.BooleanField(default=False)),
                ('child_adoption_leave', models.IntegerField()),
                ('cal_carry', models.BooleanField(default=False)),
                ('updated_by', models.CharField(max_length=50)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
