# Generated by Django 2.2.28 on 2024-11-10 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leavesetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavesetup',
            name='associate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavesetup',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
