# Generated by Django 2.2.28 on 2024-11-10 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_auto_20241110_0758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveSetup',
        ),
    ]
