# Generated by Django 2.2.28 on 2024-11-11 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0005_leavesetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_type', models.CharField(blank=True, max_length=10, null=True)),
                ('no_of_days', models.IntegerField()),
                ('leave_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('leave_apply_date', models.DateField(auto_now_add=True)),
                ('leave_approve_date', models.DateField(blank=True, null=True)),
                ('approval_id', models.CharField(blank=True, max_length=10, null=True)),
                ('approve_by', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associates_admin', to=settings.AUTH_USER_MODEL)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associate_leave_applications', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.Leave')),
            ],
        ),
    ]
