# Generated by Django 2.2.28 on 2024-11-11 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_leaveapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associates_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
