# Generated by Django 2.2.28 on 2024-11-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_auto_20241112_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='day',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
