# Generated by Django 2.2.28 on 2024-11-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0009_holiday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='no_of_days',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
