# Generated by Django 2.2.28 on 2024-11-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0010_auto_20241112_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='no_of_days',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
