# Generated by Django 2.2.28 on 2024-11-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_auto_20241112_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
