# Generated by Django 2.2.28 on 2024-11-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0012_auto_20241112_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavesetup',
            name='casual_leave',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavesetup',
            name='child_adoption_leave',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavesetup',
            name='compensatory_off',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavesetup',
            name='earned_leave',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavesetup',
            name='loss_of_pay',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavesetup',
            name='maternity_leave',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavesetup',
            name='paternity_leave',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavesetup',
            name='sick_leave',
            field=models.FloatField(),
        ),
    ]
