# Generated by Django 2.2.28 on 2024-11-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0013_auto_20241113_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='no_of_days',
            field=models.FloatField(),
        ),
    ]
