# Generated by Django 2.2.28 on 2024-11-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0014_auto_20241113_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_apply_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
