# Generated by Django 2.2.28 on 2024-11-08 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=50)),
                ('associate_id', models.CharField(max_length=20, unique=True)),
                ('employee_title', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('joining_date', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_modification_date', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_admin', to=settings.AUTH_USER_MODEL)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_associate', to=settings.AUTH_USER_MODEL)),
                ('home_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
