# Generated by Django 2.2.28 on 2024-11-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowconfiguration',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
