# Generated by Django 2.2.28 on 2024-11-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20241114_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
