# Generated by Django 2.2.28 on 2024-11-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20241114_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
